# The name of your workflow
name: IOS

# When should this workflow run?
on:
  pull_request:
    branches:
      - master

# Jobs to perform in this workflow
jobs:
  flutter_test:
    # Name of the job
    name: Run Flutter Test and analyze
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # Sets up the Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      # Gets the dependencies and builds the app
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios:
    name: Build Flutter(ios)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-iOS
          path: build/ios/iphoneos/app.ipa

  distribute-ios:
    needs: build_ios # This is important
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: app.ipa
      # Uploads the app to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
        with:
          appId: ${{secrets.FIREBASE_IOS_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: app.ipa


          #      - name: Push to Releases
          #        uses: ncipollo/release-action@v1
          #        with:
          #          artifacts: "build/ios/iphones/app.ipa"
          #          tag: ios.v1.0.${{github.run_number}}
          #          token: ${{secrets.TOKEN}}


