name: Build and Distribute iOS App

on:
  push:
    branches:
      - master

jobs:
  build-and-distribute-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # Set up the Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"

      # Install required tools
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update
      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      # Build the app
      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      # Create a temporary directory for the signed IPA file
      - name: Create temporary directory
        run: mkdir -p build/ios/ipa

      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      # ss
      # - name: Build xArchive
      #   run: xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release DEVELOPMENT_TEAM=TUBBTSR2F6 -sdk'iphones' -destination'generic/platform=iOS' -archivePath build-output/app.xcarchive PROVISIONING_PROFILE=7f0027f4a31736ebc3bb0cabc819b514607481b2 clean archive CODE_SIGN_IDENTITY= 'Apple Distribution:Jainam Shah'

      # - name: Export ipa
      #   # run: xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist
      #   run: xcodebuild -exportArchive -archivePath ./Build/demopro.xcarchive -exportPath ./Build/demopro.ipa -exportWithOriginalSigningIdentity

      - name: Publish iOS Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: release-ios
          path: ios

      # Sign the IPA file using Xcode
      - name: Sign iOS app with Xcode
        run: xcodebuild -exportArchive -archivePath app.xcarchive -exportPath ios -exportOptionsPlist ios/Runner/ExportOptions.plist

      # - name: Build xArchive
      #   run: xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release DEVELOPMENT_TEAM=
      #       # xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release DEVELOPMENT_TEAM=YOUR_TEAM_ID -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath build-output/app.xcarchive PROVISIONING_PROFILE=YOUR_UUID clean archive CODE_SIGN_IDENTITY="Apple Distribution: Damien Aicheh"

      # Upload the signed IPA file to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          releaseNotes: "This is a release for version 1.0"
          groups: "testers"
          apkPath: "build-output/ios/*.ipa"